// Generated by gencpp from file rosjava_test_msgs/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROSJAVA_TEST_MSGS_MESSAGE_ADDTWOINTS_H
#define ROSJAVA_TEST_MSGS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <rosjava_test_msgs/AddTwoIntsRequest.h>
#include <rosjava_test_msgs/AddTwoIntsResponse.h>


namespace rosjava_test_msgs
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace rosjava_test_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosjava_test_msgs::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::rosjava_test_msgs::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::rosjava_test_msgs::AddTwoInts > {
  static const char* value()
  {
    return "rosjava_test_msgs/AddTwoInts";
  }

  static const char* value(const ::rosjava_test_msgs::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::rosjava_test_msgs::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::rosjava_test_msgs::AddTwoInts > 
template<>
struct MD5Sum< ::rosjava_test_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_test_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::rosjava_test_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_test_msgs::AddTwoIntsRequest> should match 
// service_traits::DataType< ::rosjava_test_msgs::AddTwoInts > 
template<>
struct DataType< ::rosjava_test_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::rosjava_test_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::rosjava_test_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosjava_test_msgs::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::rosjava_test_msgs::AddTwoInts > 
template<>
struct MD5Sum< ::rosjava_test_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosjava_test_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::rosjava_test_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosjava_test_msgs::AddTwoIntsResponse> should match 
// service_traits::DataType< ::rosjava_test_msgs::AddTwoInts > 
template<>
struct DataType< ::rosjava_test_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::rosjava_test_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::rosjava_test_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSJAVA_TEST_MSGS_MESSAGE_ADDTWOINTS_H
